// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/glamnet/BeautyDispatch.tsx": () => import("../components/mockups/glamnet/BeautyDispatch.tsx"),
  "./components/mockups/glamnet/BeautyTimeline.tsx": () => import("../components/mockups/glamnet/BeautyTimeline.tsx"),
  "./components/mockups/glamnet/EventBooking.tsx": () => import("../components/mockups/glamnet/EventBooking.tsx"),
  "./components/mockups/glamnet/ReputationScore.tsx": () => import("../components/mockups/glamnet/ReputationScore.tsx")
};
